IF OBJECT_ID('dbo.INV_REPORTES_STOCKS', 'U') IS NOT NULL
    DROP TABLE dbo.INV_REPORTES_STOCKS;

IF OBJECT_ID('dbo.INV_PERIODOS', 'U') IS NOT NULL
    DROP TABLE dbo.INV_PERIODOS;

IF OBJECT_ID('dbo.INV_MOVIMIENTOS', 'U') IS NOT NULL
    DROP TABLE dbo.INV_MOVIMIENTOS;

IF OBJECT_ID('dbo.INV_PRODUCTOS', 'U') IS NOT NULL
    DROP TABLE dbo.INV_PRODUCTOS;

IF OBJECT_ID('dbo.INV_TIPOS_MOVIMIENTOS', 'U') IS NOT NULL
    DROP TABLE dbo.INV_TIPOS_MOVIMIENTOS;

IF OBJECT_ID('dbo.INV_TIPOS_PRODUCTOS', 'U') IS NOT NULL
    DROP TABLE dbo.INV_TIPOS_PRODUCTOS;

IF OBJECT_ID('dbo.INV_ALMACENES', 'U') IS NOT NULL
    DROP TABLE dbo.INV_ALMACENES;

IF OBJECT_ID('dbo.INV_TIPOS_DOCUMENTOS', 'U') IS NOT NULL
    DROP TABLE dbo.INV_TIPOS_DOCUMENTOS;

-- -----------------------------------------------------
-- Table INV_TIPOS_MOVIMIENTOS
-- -----------------------------------------------------
CREATE TABLE INV_TIPOS_MOVIMIENTOS (
  TIPO_MOVIMIENTO_ID INT NOT NULL,
  NOMBRE VARCHAR(45) NOT NULL,
  DESCRIPCION VARCHAR(100) NULL,
  TIPO_OPERACION VARCHAR(10) NOT NULL,  
  PRIMARY KEY (TIPO_MOVIMIENTO_ID),
  CONSTRAINT CHK_TIPO_OPERACION CHECK (TIPO_OPERACION IN ('ENTRADA', 'SALIDA'))
);


-- -----------------------------------------------------
-- Table INV_ALMACENES
-- -----------------------------------------------------
CREATE TABLE  INV_ALMACENES (
  ALMACEN_ID INT NOT NULL IDENTITY,
  NOMBRE VARCHAR(45) NOT NULL,
  ALMACEN_CENTRAL TINYINT NOT NULL,
  PRIMARY KEY (ALMACEN_ID))
;

-- -----------------------------------------------------
-- Table INV_TIPOS_PRODUCTOS
-- -----------------------------------------------------
CREATE TABLE  INV_TIPOS_PRODUCTOS (
  TIPO_PRODUCTO_ID INT NOT NULL,
  NOMBRE VARCHAR(45) NOT NULL,
  DESCRIPCION VARCHAR(100) NULL,
  PRIMARY KEY (TIPO_PRODUCTO_ID))
;


-- -----------------------------------------------------
-- Table INV_PRODUCTOS
-- -----------------------------------------------------
CREATE TABLE  INV_PRODUCTOS (
  PRODUCTO_ID INT NOT NULL IDENTITY,
  TIPO_PRODUCTO_ID INT NOT NULL,
  NOMBRE VARCHAR(45) NOT NULL,
  MARCA VARCHAR(45) NOT NULL,
  MODELO VARCHAR(45) NOT NULL,
  PRIMARY KEY (PRODUCTO_ID),
  CONSTRAINT fk_producto_tipo_producto1
    FOREIGN KEY (TIPO_PRODUCTO_ID)
    REFERENCES INV_TIPOS_PRODUCTOS (TIPO_PRODUCTO_ID)
);


-- -----------------------------------------------------
-- Table INV_TIPOS_DOCUMENTOS
-- -----------------------------------------------------
CREATE TABLE  INV_TIPOS_DOCUMENTOS (
  TIPO_DOCUMENTO_ID INT NOT NULL,
  NOMBRE VARCHAR(45) NOT NULL,
  PRIMARY KEY (TIPO_DOCUMENTO_ID))
;


-- -----------------------------------------------------
-- Table INV_MOVIMIENTOS
-- -----------------------------------------------------
CREATE TABLE  INV_MOVIMIENTOS (
  MOVIMIENTO_ID INT NOT NULL IDENTITY,
  TIPO_MOVIMIENTO_ID INT NOT NULL,
  FECHA_MOVIMIENTO DATETIME NOT NULL,
  FECHA_CREACION DATETIME NOT NULL,
  TIPO_DOCUMENTO_ID INT NOT NULL,
  NUMERO_DOCUMENTO VARCHAR(45) NOT NULL,
  ALMACEN_ID INT NOT NULL,
  PRODUCTO_ID INT NOT NULL,
  CANTIDAD INT NOT NULL,
  VALOR DECIMAL(10,3) NOT NULL,
  PRIMARY KEY (MOVIMIENTO_ID),
  CONSTRAINT fk_movimiento_tipo_movimiento1
    FOREIGN KEY (TIPO_MOVIMIENTO_ID)
    REFERENCES INV_TIPOS_MOVIMIENTOS (TIPO_MOVIMIENTO_ID),
  CONSTRAINT fk_movimiento_almacen1
    FOREIGN KEY (ALMACEN_ID)
    REFERENCES INV_ALMACENES (ALMACEN_ID),
  CONSTRAINT fk_movimiento_producto1
    FOREIGN KEY (PRODUCTO_ID)
    REFERENCES INV_PRODUCTOS (PRODUCTO_ID),
  CONSTRAINT fk_movimiento_tipo_documento1
    FOREIGN KEY (TIPO_DOCUMENTO_ID)
    REFERENCES INV_TIPOS_DOCUMENTOS (TIPO_DOCUMENTO_ID)
);


-- -----------------------------------------------------
-- Table INV_PERIODOS
-- -----------------------------------------------------
CREATE TABLE  INV_PERIODOS (
  ANHO INT NOT NULL,
  MES INT NOT NULL,
  DESCRIPCION VARCHAR(45) NOT NULL,
  PRIMARY KEY (ANHO, MES))
;


-- -----------------------------------------------------
-- Table INV_REPORTES_STOCKS
-- -----------------------------------------------------
CREATE TABLE  INV_REPORTES_STOCKS (
  ANHO INT NOT NULL,
  MES INT NOT NULL,
  PRODUCTO_ID INT NOT NULL,
  ALMACEN_ID INT NOT NULL,
  SALDO_INICIAL INT NOT NULL,
  ENTRADAS INT NOT NULL,
  SALIDAS INT NOT NULL,
  SALDO_FINAL INT NOT NULL,
  PRIMARY KEY (ANHO, MES, PRODUCTO_ID, ALMACEN_ID),
  CONSTRAINT fk_kardex_periodo1
    FOREIGN KEY (ANHO , MES)
    REFERENCES INV_PERIODOS (ANHO , MES),
  CONSTRAINT fk_kardex_producto1
    FOREIGN KEY (PRODUCTO_ID)
    REFERENCES INV_PRODUCTOS (PRODUCTO_ID),
  CONSTRAINT fk_kardex_almacen1
    FOREIGN KEY (ALMACEN_ID)
    REFERENCES INV_ALMACENES (ALMACEN_ID)
);